### PR TITLE
Render-based refactor: Step 3

### PR DESCRIPTION
**Pull request by coderkevin**
WIP

Continuing in Step 3 of the refactor, this uses the scheduler and requests objects. This changes the ApiClient from tracking the requirements of each component to simply scheduling out requests based on components as they render. i.e. We don't refresh the list of requirements, we just make sure that the next fetch of needed resources is set up correctly. When that fetch happens, it updates the data state, which causes each component to re-render, sending its requirements once again, which starts the cycle over.

The advantage to this is simplification, and no longer needing to keep track of which component needs which resources in which way. We simply update our set of scheduled requests every time a component is rendered to make sure that they're taken care of. If the component is unmounted before the request returns, then the component will simply not be there to require that resource next time around.

To Test:
This is still a work in progress and testing instructions have yet to be written.

### CODE REVIEW

**Comment by v18** [comment]
Hey, I've got a question about the approach. I recognize this is a work in progress so you may not have all the answers :)

> If the component is unmounted before the request returns, then the component will simply not be there to require that resource next time around.

This means that if a component was the only one to require a certain resource, and it gets unmounted, then that resource still gets fetched (once). Is that a tradeoff we're making - being ok with at most one excess network request after a component gets unmounted, in order to simplify the logic?

**Comment by coderkevin** [comment]
> This means that if a component was the only one to require a certain resource, and it gets unmounted, then that resource still gets fetched (once). Is that a tradeoff we're making - being ok with at most one excess network request after a component gets unmounted, in order to simplify the logic?

Yes, this is the case. There are a couple other benefits of this approach as well, better visibility of the scheduled updates for one, and some better support for stacking up mutations together as well (which tends to happen in applications like WooCommerce where multiple batch updates can occur.)

**Comment by v18** [comment]
Thanks Kevin for elaborating. Didn't mean to imply the tradeoff wasn't worth it, just pointed out one benefit since it's the only one I knew about at the time :)

**Comment by coderkevin** [comment]
Closing in favor of #202

**Pull request closed without merging**
