### PR TITLE
Update babel to 7

### PR DESCRIPTION
**Pull request by coderkevin**
Wow, this is a lot of lines, but this is all build stuff and no real code changes exist in this PR.
It will need some testing though.

Also, known issue: The example apps use an older version of `react-scripts` with a security vulnerability. But it's only when they're being served locally. That will be a topic for another PR to update them all to CRA2.

(Edit: I created #104 to track the above issue)

## To Test:

1. `npm install`
2. `npm run bootstrap` (this will take a while)
3. `npm run build`
4. `npm run lint`
5. `npm test`
6. Test each example app by:
  a. `cd examples/<app>`
  b. `npm install`
  c. `npm start`
  c. Browser tab should open, try out app and make sure it works.

### CODE REVIEW

**Comment by coderkevin** [comment]
I completely deleted all `node_module` folders in my repo and tried again and the tests worked for me. Would you mind doing that?

`rm -r node_modules packages/framework/node_modules packages/react-provider/node_modules`
then starting over on the instructions should do the trick.

As for the vulnerability, it's related to the version of create-react-app that the examples are using.  I've created #104 to track it.

**Comment by belcherj** [comment]
`a. cd example/<app>` . This should be `examples`

**Comment by belcherj** [comment]
I did have 6 package-lock changes after doing all the installs.

**Comment by coderkevin** [comment]
Thanks @belcherj! there's not a whole lot of code to look at here as the changes are only what's necessary to update to babel 7.

**Pull request merged**
